### ISSUE TITLE
Support streaming collections

### ISSUE THREAD

**Issue by EliasDeuss** [excogitatr/paginate_firestore#1]
Could you add an option to use a collection stream with this widget?

**Comment by dekadevelop** [comment]
I would love to use it with StreamProvider

**Comment by Matthuffy** [comment]
Definitely a must

**Comment by azazadev** [comment]
any news about support of collection stream ?  Thanks

**Comment by reanyouda** [comment]
any news about support of collection stream ? Thanks

**Comment by rajflutter** [comment]
whenever we add/update document data, it is not reflecting, will this be solved if you introduce steam provider and plans when we can expect it?

**Comment by excogitatr** [comment]
It is being worked on. I highly appreciate your patience guys.

**Comment by reanyouda** [comment]
> It is being worked on. I highly appreciate your patience guys.

how long does it take brother ?

**Comment by azazadev** [comment]
> It is being worked on. I highly appreciate your patience guys.

Thanks !!!, this is a very critical problem for us

**Comment by ArjanAswal** [comment]
Any updates on this?
This is a very important feature and would make the plugin even more useful.

**Comment by xanf-code** [comment]
Any update ?

**Comment by azazadev** [comment]
@excogitatr no pressure but do you have an estimated date for this feature as the task is open and not in progress since 7 months ?
Thanks

**Comment by ArjanAswal** [comment]
@azazadev Seconded
@excogitatr How will you implement this feature? Can you provide a rough timeline?

**Comment by marciovalim** [comment]
@excogitatr Any update?

**Comment by marciovalim** [comment]
I couldn't wait for this feature, so I implemented my own solution. Maybe it will help someone else.
https://pub.dev/packages/realtime_pagination

**Comment by ujwalchordiya** [comment]
Absolutely wonderful. Used it for a project. Works perfectly. Thanks

**Comment by ujwalchordiya** [comment]
When you remove a document from from firestore which is displaying on screen, everything is shuffled. Can you please fix that?

**Comment by marciovalim** [comment]
Sure

**Comment by azazadev** [comment]
> I couldn't wait for this feature, so I implemented my own solution. Maybe it will help someone else.
> https://pub.dev/packages/realtime_pagination

Thanks @marciovalim for the effort

**Comment by azazadev** [comment]
> When you remove a document from from firestore which is displaying on screen, everything is shuffled. Can you please fix that?

@ujwalchordiya please do not use this room  to discuss other package issue, you can create ticket on the dedicated package to track issues

**Comment by azazadev** [comment]
as no update since long time I'm moving to https://pub.dev/packages/firestore_collection and will test also @marciovalim solution

**Comment by reanyouda** [comment]
> as no update since long time I'm moving to https://pub.dev/packages/firestore_collection and will test also @marciovalim solution

can i get more documents for the newbie?

**Comment by azazadev** [comment]
> > as no update since long time I'm moving to https://pub.dev/packages/firestore_collection and will test also @marciovalim solution
> 
> can i get more documents for the newbie?

@reanyouda yes, I have suggest this Example : https://github.com/furkansarihan/firestore_collection/issues/1#issuecomment-741978372
demo : https://drive.google.com/file/d/1qORfFYFKvJOuzIAqJn5bqrtnmyLDDmNu/view?usp=sharing

@all  again please out of respect for the author of this package do not use this room to discuss about others packages issue

**Comment by reanyouda** [comment]
> > > as no update since long time I'm moving to https://pub.dev/packages/firestore_collection and will test also @marciovalim solution
> > 
> > 
> > can i get more documents for the newbie?
> 
> @reanyouda yes, I have suggest this Example : [furkansarihan/firestore_collection#1 (comment)](https://github.com/furkansarihan/firestore_collection/issues/1#issuecomment-741978372)
> demo : https://drive.google.com/file/d/1qORfFYFKvJOuzIAqJn5bqrtnmyLDDmNu/view?usp=sharing
> 
> @ALL again please out of respect for the author of this package do not use this room to discuss about others packages issue

I got the message like this and cannot find out what happened ( RangeError (index): Invalid value: Not in inclusive range 0..14: 15 )

**Comment by reanyouda** [comment]
> > > as no update since long time I'm moving to https://pub.dev/packages/firestore_collection and will test also @marciovalim solution
> > 
> > 
> > can i get more documents for the newbie?
> 
> @reanyouda yes, I have suggest this Example : [furkansarihan/firestore_collection#1 (comment)](https://github.com/furkansarihan/firestore_collection/issues/1#issuecomment-741978372)
> demo : https://drive.google.com/file/d/1qORfFYFKvJOuzIAqJn5bqrtnmyLDDmNu/view?usp=sharing
> 
> @ALL again please out of respect for the author of this package do not use this room to discuss about others packages issue

I want example with pagination please

**Comment by excogitatr** [comment]
Sorry for the delay guys! Finally this has been solved. I have pushed an update v0.3.0. Let me know if it is working well.
