### ISSUE TITLE
Update Bloc Library

### ISSUE THREAD

**Issue by Arjunraj-k** [excogitatr/paginate_firestore#12]
Because every version of paginate_firestore depends on flutter_bloc ^4.0.0 and project depends on flutter_bloc ^5.0.1, paginate_firestore is forbidden.

So, because project depends on paginate_firestore ^0.1.1, version solving failed.
pub get failed (1; So, because project depends on paginate_firestore ^0.1.1, version solving failed.)

**Comment by excogitatr** [comment]
I will update in the next release @Arjunraj-k

**Comment by excogitatr** [comment]
Bloc version has been updated. Thanks for using the package, hope it helped!
