### ISSUE TITLE
is it possible to use a future in within the itemBuilder ?

### ISSUE THREAD

**Issue by ben55j** [excogitatr/paginate_firestore#123]
Hello, 

The item data I am using for building my paginated list requires a second Firestore query to get fully displayed.
The problem is that I can't figure out how to manage that, because the itemBuilder seems not accepting any future.
 
Do you have any example that could help with this ?

Thank you,
Benjamin

**Comment by vedartm** [comment]
Hi @ben55j. Thanks for using the package. `itemBuilder` does not support future now. Instead, you can wrap each item with a `FutureBuilder`

Feel free to reopen this if you face this issue again.
