### ISSUE TITLE
OnEmpty does not work good

### ISSUE THREAD

**Issue by ghanemnagi** [excogitatr/paginate_firestore#145]
In the new update onEmpty show full screen (placeholder expanded to fill overall screen) and may user doesn't see the placeholder unless he scroll down.

Please return it back to fit the placeholder height.
Thanks

**Comment by demanhamed** [comment]
Just get in PaginateFirestore class (ctr + click if you are using vs code), and scroll down to _buildWithScrollView function ,inside this fuction all u have to do is to remove SingleChildScrollView widget (keep only  the Container widget ), and that's it :)

**Comment by ghanemnagi** [comment]
@Elhushiy Thank you! your solution is right, I tried to change the onEmpty itself but it didn't work.
Thanks
