### ISSUE TITLE
Hey I want list to navigate to data of that particular item 

### ISSUE THREAD

**Issue by som310** [excogitatr/paginate_firestore#20]
Hey I want list to navigate to data of that particular item  how can I do that please guide me

**Comment by excogitatr** [comment]
I am not sure if it is possible with the current version. Although I am guessing providing a list view controller might solve it.

**Comment by excogitatr** [comment]
You can add your custom `ScrollController` using `scrollController` attribute which will help in scrolling to an item. Try this [blog](https://cogitas.net/scroll-position-flutter-listview/) for reference.

Thanks for using the package 🎉  Feel free to reopen issue if you face similar issue.
