### ISSUE TITLE
auto scrolling function 

### ISSUE THREAD

**Issue by Janghwi** [excogitatr/paginate_firestore#21]
Thank you for contributing your excellent package. 
Would it be possible to scroll automatically according to the given timer setting value?
Except basic ui, I want to use this package for upper screen on youtube screen and lower paginated firestore text data. 
Thanks!

**Comment by excogitatr** [comment]
You can add your own custom `scrollController` in v0.2.0 using the function `_scrollController.animateTo()`. If it does not help, feel free to reopen the issue
