### ISSUE TITLE
Please add a simple Search Bar or implement a way to filtering the results

### ISSUE THREAD

**Issue by carpiodanielj** [excogitatr/paginate_firestore#23]
I want a simple Search Bar built-in in the top of the list or maybe a way to implement my own search bar for filtering the results.

I mean something like this:

![Screenshot_2018-08-27-16-39-55-300_com infodat akeepo](https://user-images.githubusercontent.com/13338743/92176803-d5a71c00-ee04-11ea-9e5a-63493cef4f73.png)

**Comment by Omi231** [comment]
+1

That will be amazing <3

**Comment by excogitatr** [comment]
You can implement your search bar with `PaginateSearchChangeListener` implemented in v0.2.0

**Comment by excogitatr** [comment]
Thanks for using the package 🎉 Feel free to reopen issue if you face similar issue.
