### ISSUE TITLE
Switch between ListView to GridView

### ISSUE THREAD

**Issue by rajflutter** [excogitatr/paginate_firestore#26]
can you provide us a method to switch between ListView to GridView based on user click on button

**Comment by excogitatr** [comment]
For now you can currently change the state of `PaginateFirestore` widget (with a `setState` maybe) and update the `itemBuilderType` on button click.

**Comment by excogitatr** [comment]
Thanks for using the package 🎉 Feel free to reopen issue if you face similar issue.
