### ISSUE TITLE
Limit items per page and know when is fetching more documents

### ISSUE THREAD

**Issue by d-apps** [excogitatr/paginate_firestore#3]
Can we control the limit of items per page? if so, how?

How to know when is fetching more documents, like a bool variable, to show some CircularProgressIndicator with "loading more data" to the user?

**Comment by excogitatr** [comment]
There is an attribute `itemsPerPage` to set number of items in one page. You can use it like this
```dart
      PaginateFirestore(
        itemBuilder: (context, documentSnapshot) => ListTile(
          leading: CircleAvatar(child: Icon(Icons.person)),
          title: Text(documentSnapshot.data['name']),
          subtitle: Text(documentSnapshot.documentID),
        ),
        // orderBy is compulsary to enable pagination
        query: Firestore.instance.collection('users').orderBy('name'),
        itemsPerPage: 10
      ),
```

**Comment by excogitatr** [comment]
I am closing the issue now. If you face any related issue, feel free to reopen it. Thanks for using the package, hope it solved your use case.

**Comment by waletoyo1** [comment]
When "itemsPerPage" attribute is used, can the "limit" method be used  together? Thanks.

**Comment by vedartm** [comment]
`itemsPerPage` internally uses firestore's `limit` method anyways @waletoyo1

**Comment by waletoyo1** [comment]
Thanks
