### ISSUE TITLE
scrolling header and footer

### ISSUE THREAD

**Issue by jenniestrongbow** [excogitatr/paginate_firestore#31]
Could you please add options to add scrolling a header and a footer?

Thanks

**Comment by excogitatr** [comment]
Can you please give an example. What exactly do you mean my scrolling a header?

**Comment by comyuno** [comment]
That would be great if you could set the first (like a headline) and the last widget (like a footer) in the "list".

**Comment by jenniestrongbow** [comment]
@comyuno, exactly!

**Comment by jenniestrongbow** [comment]
@excogitatr, any chance you might add this feature? Thanks

**Comment by jenniestrongbow** [comment]
Looks like this is no longer maintained. Pity.

**Comment by excogitatr** [comment]
Hey @jenniestrongbow. Sorry for the delay in reply. I have implemented `header` and `footer` in the latest version v0.2.2. I highly appreciate your patience.

**Comment by excogitatr** [comment]
Feel free to reopen this issue if you face similar issue. Thanks for using this package 🎉

**Comment by jenniestrongbow** [comment]
@excogitatr , fantastic! Thanks for your work and sorry about my lack of patience. :-)
