### ISSUE TITLE
Adding a new document

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [excogitatr/paginate_firestore#32]
Hello,

I'm implementing a simple chat using firestore, and I need a pagination. and this library sounds amazing, it handles loaders, pagination, search, all the stuff. Thanks!

However, I want to add a new document to the collection. the new document is not appended to the list view but it's added in the collection in firestore. and it works if I refresh the listview.

Is there any good way to add elements without refreshing the list?

**Comment by excogitatr** [comment]
Sorry! refreshing the listview is the solution for now. But it can done when streaming is implemented.

**Comment by AhmedNourJamalElDin** [comment]
Thanks @excogitatr , I'm closing in favor of #1
