### ISSUE TITLE
Using in ListView

### ISSUE THREAD

**Issue by gtilson** [excogitatr/paginate_firestore#4]
Is it possible to use this widget inside a ListView? It seems that all elements are loaded when I put it in a ListView.

**Comment by excogitatr** [comment]
Yes, it can be used inside ListView. This widget is similar to ListView and has all the attributes inside ListView (like `shrinkWrap` and all). The process is similar to adding a list view inside a list view.

**Comment by excogitatr** [comment]
I hope it answered your question. Feel free reopen this issue if you face any related issue. 🥂

**Comment by gtilson** [comment]
I am still having trouble with this. When I use the package in the implementation below, the debug console shows that the query returns everything on load, even when some are not visible.

`  buildComments() {
    return PaginateFirestore(
          shrinkWrap: true,
          initialLoader: circularProgress(),
          itemsPerPage: 5,
          itemBuilder: (context, documentSnapshot) => ListTile(
            leading: CircleAvatar(backgroundImage: CachedNetworkImageProvider(Comment.fromDocument(documentSnapshot).avatarUrl)),
            title: Text(Comment.fromDocument(documentSnapshot).comment),
            subtitle: Text(timeago.format(Comment.fromDocument(documentSnapshot).timestamp.toDate())),
          ),
          query: commentsRef
        .document(postId)
        .collection('comments')
        .orderBy('timestamp', descending: false),
        );
  }`

`@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(child: Column(
        children: <Widget>[
          Padding(padding: EdgeInsets.only(top: 10), child:Text('Comments')),
          Expanded(child: buildComments()),
          Divider(),
          ListTile(
            title: TextFormField(
              controller: commentController,
              decoration: InputDecoration(labelText: "Write a comment..."),
            ),
            trailing: OutlineButton(
              onPressed: addComment,
              borderSide: BorderSide.none,
              child: Text("Post"),
            ),
          ),
        ],
      ),) 
    );
  }
}`

**Comment by gtilson** [comment]
I know that it can be used inside ListView; however, when it is used inside ListView everything is loaded upon build.

**Comment by excogitatr** [comment]
When you add this widget inside a listview it is not paginating (or lazy loading) it is directly loading all the list is what you are saying right?

In that case, this happens for the first 2 pages at least. Lets consider you have list of 100 items and 10 is the page size. When you put it in a list view it loads 2 or 3 pages (i.e 30 items) before hand but it still paginates after the 2nd or 3rd page. This happens because next page is fetched only when the last item of previous page is built and the outer listview forces it load items before hand.

**Comment by excogitatr** [comment]
@gtilson  I use this as a solution. Instead of using an outer list view, I use preload items and put `buildProfileHeader()` if the item is null. For example

```dart
      PaginationView(
        preloadedItems: [null],
        itemBuilder: (_, idea) => (idea == null)
            ? buildProfileHeader()
            : buildListItem(),
        pageFetch: (offset) => // necessary query ,
        onError: (error) => // error widget,
      )
```

**Comment by mohdtaha60** [comment]
> @gtilson I use this as a solution. Instead of using an outer list view, I use preload items and put `buildProfileHeader()` if the item is null. For example
> 
> ```dart
>       PaginationView(
>         preloadedItems: [null],
>         itemBuilder: (_, idea) => (idea == null)
>             ? buildProfileHeader()
>             : buildListItem(),
>         pageFetch: (offset) => // necessary query ,
>         onError: (error) => // error widget,
>       )
> ```

How to Preload in PaginateFirestore?

**Comment by excogitatr** [comment]
In the latest version (v0.2.2) `header` and `footer` support has been added. Now you can simply pass `buildProfileHeader()` in `header` attribute

**Comment by excogitatr** [comment]
@mohdtaha60 `preloadedItems` attribute is basically list of objects that you already have locally instead of fetching it from firestore. You just have to pass a list of objects in `preloadedItems`
