### ISSUE TITLE
Is there a way to change query dynamically ? 

### ISSUE THREAD

**Issue by ganeshchenniah** [excogitatr/paginate_firestore#41]
Hi i have used bool variable, setState, changenotifier. None of them worked . Please let me know if it is possible ?

Thank You

**Comment by excogitatr** [comment]
Try adding a key to PaginateFirestore widget and change it when you change the state. But this will reload the whole pagination view

**Comment by ganeshchenniah** [comment]
yes, it worked after key addition.
Thank you
