### ISSUE TITLE
package status

### ISSUE THREAD

**Issue by azazadev** [excogitatr/paginate_firestore#48]
Hi
I would like to have a status about this package, so @excogitatr @adamdupuis @claudemircasa @imhafeez @GauthamAsir all others contributors if it's possible to have answer of those questions :

- do you have stop working on this package ? if yes please inform 
- any news about Support of streaming ?
- do you plan to add cache query support ?
- package is not up to date with last firestore version, so we cannot upgrade firebase due to this, so any plan to do this ?
- what about open bugs ? there is no answer since 23 days for new open bugs 

Thank you for your understanding

**Comment by excogitatr** [comment]
Hi @azazadev. The package is not discontinued. I have pushed an update (**v0.3.0**) which will solve most of the issues that you mentioned. Please test it and let me know.

**Comment by azazadev** [comment]
Thanks @excogitatr for the update !!!
I will try to test latest version this week
do you know if there is a plan to support caching query ? as you know we cannot imagine usage of firestore without caching for most of use case, just close and open the app will trigger new docs read if no local cache configured ( more cost :) )

to give you idea I'm using this package on some views and caching is work perfectly 
https://github.com/furkansarihan/firestore_collection/blob/master/lib/firestore_collection.dart
