### ISSUE TITLE
Refresh stream from Page first

### ISSUE THREAD

**Issue by hilalbaig** [excogitatr/paginate_firestore#5]
How can I refresh PaginateFirestore from start?

**Comment by excogitatr** [comment]
You can rebuild the while widget by changing the key of `PaginateFirestore` widget. Check this [link](https://github.com/excogitatr/pagination_view/issues/1)

**Comment by hilalbaig** [comment]
> You can rebuild the whole widget by changing the key of `PaginateFirestore` widget. Check this [link](https://github.com/excogitatr/pagination_view/issues/1)

That worked 👍
