### ISSUE TITLE
cache query

### ISSUE THREAD

**Issue by azazadev** [excogitatr/paginate_firestore#56]
Hi,
any plan to support cache query ? as you know we cannot imagine usage of firestore without caching for most of use case, just close and open the app will trigger new docs read if no local cache configured

**Comment by m-j-g** [comment]
If you set the "isLive" parameter to true it uses snapshots() instead of get().  snapshots() loads from cache by default correct?  Only triggers reads if there has been an update?

**Comment by excogitatr** [comment]
As @m-j-g mentioned, you can set `isLive` to true which will use snapshots which in turn helps with caching.

**Comment by excogitatr** [comment]
Thanks for using the package. Feel free to reopen if you face any similar issues.

**Comment by p4-k4** [comment]
Firstly, thanks for putting this package together, literally saved me!

Regarding this issue, how feasible is it to allow users to set a timeout on whether or not we're fetching from the cache or server?

In the case of data that won't be stale for a few days, we could drastically reduce document reads but this would obviously be quite project specific.

Thanks
