### ISSUE TITLE
StreamSubscription needs to be closed

### ISSUE THREAD

**Issue by ghprod** [excogitatr/paginate_firestore#59]
Hi

Thanks for your package. It saves a lot of my time :+1: 

Btw, I noticed that when using `isLive` option as `true`, the stream is always active even we moved into another screen.

We need to capture the `StreamSubscription` from this line https://github.com/excogitatr/paginate_firestore/blob/master/lib/bloc/pagination_cubit.dart#L86 and `cancel()` on `dispose`.

Something like this

```dart

List<StreamSubscription<QuerySnapshot>>() streams = List<StreamSubscription<QuerySnapshot>>();

...

_getLiveDocuments() {
    ...
      StreamSubscription listener = localQuery.snapshots().listen((querySnapshot) {
        _emitPaginatedState(
          querySnapshot.docs,
          previousList:
              loadedState.documentSnapshots as List<QueryDocumentSnapshot>,
        );
      });
    }

  streams.add(listeners);
  }

...

streams.forEach((listener) => listener.cancel());
```

Thanks

**Comment by excogitatr** [comment]
Thanks for making a PR @ghprod. I will be released with the next version. Feel free to reopen it if you face a similar issue.
