### ISSUE TITLE
How to change the default no documents found message

### ISSUE THREAD

**Issue by devDonald** [excogitatr/paginate_firestore#63]
Please I need to change the default **no document found** message when there are no documents found. I have used:

`if(snapshot.data().isEmpty  || snapshot.data().length < 1 || !snapshot.data().isNotEmpty){

return Container(
                margin: EdgeInsets.only(top: 170),
                child: NoDataAvailable(
                  message: 'No Video posts Yet',
                ),
              );
}`

but i still get the **no document found** message

**Comment by excogitatr** [comment]
Hey @devDonald! You can use `emptyDisplay` attribute which accepts a Widget that can be anything of your choice (Different text or even image).

**Comment by excogitatr** [comment]
Thanks for using the package. Hope this helps with the issue. Feel free to reopen this if you face any similar issues.
