### ISSUE TITLE
GridView is not change size of Container

### ISSUE THREAD

**Issue by puttuverma** [excogitatr/paginate_firestore#64]
In my code ListView is a perfect run but GridView Container size is not changeble so please help me or add new options to change GridView design

**Comment by excogitatr** [comment]
Hey @puttuverma! You can change the grid view settings with `gridDelegate`. Use [SliverGridDelegateWithFixedCrossAxisCount()](https://api.flutter.dev/flutter/rendering/SliverGridDelegateWithFixedCrossAxisCount-class.html) to change spacing, aspect ratio, grid count or anything.

**Comment by excogitatr** [comment]
Thanks for using the package. Feel free to reopen this if you face any similar issues.
