### ISSUE TITLE
Rebuild with a new querry

### ISSUE THREAD

**Issue by ben55j** [excogitatr/paginate_firestore#69]
Hello, 

I am trying to implement a search bar, and I need to change the query for every new search.
Problem: The list does not refresh itself when I am changing the query using a setState.

Is it supposed to work that way? Do you recommend another solution ?

Thank you for your help,
Benjamin

**Comment by excogitatr** [comment]
Hi @ben55j. When you change the state, change the key of the `PaginateFirestore` widget as well by changing its `key`.

**Comment by ben55j** [comment]
Works great, thank you!

**Comment by excogitatr** [comment]
Thanks for using the package.
