### ISSUE TITLE
Circular progress doesn't disappear

### ISSUE THREAD

**Issue by itssidhere** [excogitatr/paginate_firestore#71]
when we use where clause in the query and the collection has only one document. The circular progress indicator at the end doesn't disappear.

My config

`
Column(
children:[
Container (height: 200),
Expanded(
child:PaginateFirestore(shrinkWrap:true)

]

)
`

**Comment by anilmuppalla** [comment]
@itssidhere  What was the solution, this is happening to me as well

**Comment by itssidhere** [comment]
@anilmuppalla I can't recall exactly but i think the issue was related to creating an index in the firestore. You must have an index corresponding to your where clause

**Comment by anilmuppalla** [comment]
perfect! thank you!
